name: LeetCode Test

on: [push, repository_dispatch]

jobs:
  go-test:
    name: Run unit testcases on ${{ matrix.os }} with Go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:        
        go_version: [1.17]        
        os: [ubuntu-latest]

    steps:
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: |
          go test -v ./...
